name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
    
     - name: Login to GitHub Container Registry
       uses: docker/login-action@v1
       with:
        registry: ghcr.io
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}
        
     - name: Build the Docker image
       run: |
        docker build . --file Dockerfile --tag first-image:$(date +%s)
        docker push ghcr.io/${{ secrets.USERNAME }}/first-image:$(date +%s)
      
